(function(){function V(){var a=this;a.installed=!1;a.raw="";a.major=-1;a.minor=-1;a.revision=-1;a.revisionStr="";var f=[{name:"ShockwaveFlash.ShockwaveFlash.7",version:function(a){return b(a)}},{name:"ShockwaveFlash.ShockwaveFlash.6",version:function(a){var f="6,0,21";try{a.AllowScriptAccess="always",f=b(a)}catch(g){}return f}},{name:"ShockwaveFlash.ShockwaveFlash",version:function(a){return b(a)}}],b=function(a){var f=-1;try{f=a.GetVariable("$version")}catch(b){}return f};a.FlashDetect=function(){var b,
c,g,k,s;if(navigator.plugins&&0<navigator.plugins.length){var n=navigator.mimeTypes;if(n&&n["application/x-shockwave-flash"]&&n["application/x-shockwave-flash"].enabledPlugin&&n["application/x-shockwave-flash"].enabledPlugin.description){b=n=n["application/x-shockwave-flash"].enabledPlugin.description;var n=b.split(/ +/),h=n[2].split(/\./),n=n[3];c=parseInt(h[0],10);g=parseInt(h[1],10);k=n;s=parseInt(n.replace(/[a-zA-Z]/g,""),10)||a.revision;a.raw=b;a.major=c;a.minor=g;a.revisionStr=k;a.revision=
s;a.installed=!0}}else if(-1==navigator.appVersion.indexOf("Mac")&&window.execScript)for(n=-1,h=0;h<f.length&&-1==n;h++){b=-1;try{b=new ActiveXObject(f[h].name)}catch(u){b={activeXError:!0}}b.activeXError||(a.installed=!0,n=f[h].version(b),-1!=n&&(b=n,k=b.split(","),c=parseInt(k[0].split(" ")[1],10),g=parseInt(k[1],10),s=parseInt(k[2],10),k=k[2],a.raw=b,a.major=c,a.minor=g,a.revision=s,a.revisionStr=k))}}()}function h(){this.DetectBrowser=function(){var a=h.UNKNOWN;typeof window.opera!==q&&window.opera.buildNumber!==
q?a=h.OPERA:typeof window.mozInnerScreenY!==q?a=h.FIREFOX:typeof window.chrome!==q&&typeof window.chrome.app!==q?a=h.CHROME:typeof window.WebKitPoint!==q?a=h.SAFARI:typeof window.attachEvent!==q&&(a=h.IE);return a};this.DetectIEVersion=function(){var a=h.IE_VERSION_UNKNOWN;window.atob?a=h.IE_VERSION_10:document.addEventListener?a=h.IE_VERSION_9:window.JSON&&document.querySelector?a=h.IE_VERSION_8:window.XMLHttpRequest?a=h.IE_VERSION_7:document.compatMode&&(a=h.IE_VERSION_6);return a};this.DetectActualIEBrowserVersion=
function(){var a=document.createElement("div"),f="Unknown";try{a.style.behavior="url(#default#clientcaps)",f=a.getComponentVersion("{89820200-ECBD-11CF-8B85-00AA005B4383}","componentid").replace(/,/g,".")}catch(b){}return f};this.DetectDocumentMode=function(){return document&&document.documentMode?parseFloat(document.documentMode):h.IE_VERSION_UNKNOWN};this.ScreenSize=function(){return[screen.availWidth,screen.availHeight]};this.ClientTimezone=function(){return(new Date).getTimezoneOffset()};this.ClientLanguage=
function(){return window.navigator.userLanguage||window.navigator.language};this.CookiesAvailable=function(){return navigator.cookieEnabled||"cookie"in document&&(0<document.cookie.length||-1<(document.cookie="test").indexOf.call(document.cookie,"test"))}}function ea(){this.FindWindowDepth=function(a){for(var f=0,b=a.top;a!=b&&20>=f;)a=a.parent,f++;20<f&&(f=-1);return f};this.FindTopReachableWindow=function(a,f){if(-1==f)return[a,f];var b=this.GetAncestors(a);if(null===b)try{for(var e=a.top;a!=e;)a.parent.location.href,
a=a.parent,f--}catch(d){}else{for(var e=a.location.origin,g=f,k=b.length-1;0<=k;k--)b[k]==e&&(g=k);for(;f!=g;)f--,a=a.parent}return[a,f]};this.SearchTopDownReachable=function(a,b,c){if(0==b||null!==this.GetAncestors(c))return[null,-1];c=[];c.push({win:a,depth:0});for(a=0;0<c.length&&200>=a;){var e=c.shift(),d=e.win,e=e.depth;if(e>=b)break;try{return d.location.href,[d,e]}catch(g){}for(var k=0;k<d.frames.length;k++)c.push({win:d.frames[k],depth:e+1});a++}return[null,-1]};this.DetectUrl=function(a,
b){return 0==b?a.location.href:a.document.referrer};this.GetAncestors=function(a){a=a.location.ancestorOrigins;var b;b="undefined"===typeof a?"undefined":null===a?"null":Object.prototype.toString.call(a).match(/^\[object\s(.*)\]$/)[1];if("DOMStringList"==b){b=[];for(var c=0;c<a.length;c++)b[c]=a.item(c).toString();a=b}void 0===a&&(a=null);return a}}function E(){this.FindObjectPosition=function(a,b){return a.getBoundingClientRect?this.FindObjectPositionRect(a,b):this.FindObjectPositionOffset(a)};this.FindObjectPositionOffset=
function(a){var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}return[c,b]};this.FindObjectPositionRect=function(a,b){var c=a.getBoundingClientRect(),e=b.document.body,d=b.document.documentElement,g=this.GetPageScroll(b),k=c.left+g[0]-(d.clientLeft||e.clientLeft||0);return[Math.round(c.top+g[1]-(d.clientTop||e.clientTop||0)),Math.round(k)]};this.ComputeVisible=function(a,b,c,e){var d=this.FindObjectPosition(a,b),g=d[0],d=d[1],k=this.GetViewportHeight(b);b=this.GetViewportWidth(b);
var s=this.GetHeight(a);a=this.GetWidth(a);return this.ComputeVisiblePercent(d,g,a,s,b,k,c,e)};this.ComputeVisiblePercent=function(a,b,c,e,d,g,k,s){var n=0;0>a?n=Math.max(c+a,0):(n=a-k,n=Math.min(c,Math.min(c+n,d-n)));d=0;0>b?d=Math.max(e+b,0):(b-=s,d=Math.min(e,Math.min(e+b,g-b)));if(0>n||0>d)return 0;c*=e;return 0>=c?0:d*n/c};this.ComputeInitiallyVisible=function(a,b){return this.ComputeVisible(a,b,0,0)};this.ComputeCurrentlyVisible=function(a,b){var c=this.GetPageScroll(b);return this.ComputeVisible(a,
b,c[0],c[1])};this.IsVisible=function(a){return a>=E.VISIBILITY_MINIMUM&&!this.IsTabbedOut()};this.GetPageScroll=function(a){var b,c;a.pageYOffset?(c=a.pageYOffset,b=a.pageXOffset):a.document.documentElement&&a.document.documentElement.scrollTop?(c=a.document.documentElement.scrollTop,b=a.document.documentElement.scrollLeft):a.document.body&&(c=a.document.body.scrollTop,b=a.document.body.scrollLeft);return[b,c]};this.GetViewportWidth=function(a){return a.document.documentElement.clientWidth};this.GetViewportHeight=
function(a){return a.document.documentElement.clientHeight};this.GetWidth=function(a){return parseInt(a.clientWidth)};this.GetHeight=function(a){return parseInt(a.clientHeight)};this.GetSize=function(a){return[this.GetWidth(a),this.GetHeight(a)]};this.ComputeVolume=function(a){return this.GetWidth(a)*this.GetHeight(a)};this.IsTabbedOut=function(){return"hidden"==window.currentVisibility};this.CheckForObstruction=function(a,b){var c=!1;if(typeof b.document.elementFromPoint!==q){var e=this.FindObjectPosition(a,
b),d=this.GetSize(a),e=b.document.elementFromPoint(Math.floor(e[0]+d[0]/2),Math.floor(e[1]+d[1]/2));null!==e&&(c=e!==a)}return c};this.FindScript=function(){for(var a=document.getElementsByTagName("script"),b=0;b<a.length;b++){var c=a[b].src;if(0<=c.indexOf(L))return[a[b],c]}return null};this.FindAd=function(a){for(var b=["iframe","img","a","object","embed"],c=null,e=-1,d=0;d<b.length;d++)for(var g=a.getElementsByTagName(b[d]),k=0;k<g.length;k++){var s=g[k],n=this.ComputeVolume(s);n>e&&(e=n,c=s)}return c}}
function z(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;window.currentVisibility=a.type in b?b[a.type]:document[w]?"hidden":"visible"}function fa(){this.ScreenPos=function(a){var b=0;typeof a.screenX!==q?b=a.screenX:typeof a.screenLeft!==q&&(b=a.screenLeft);var c=0;typeof a.screenY!==q?c=a.screenY:typeof a.screenLeft!=q&&(c=a.screenTop);return[b,c]};this.FullWindowSize=function(a){var b=0,c=0;typeof a.outerWidth!==
q&&(b=a.outerWidth);typeof a.outerHeight!==q&&(c=a.outerHeight);return[b,c]};this.FirefoxWindowPosition=function(a){var b=0,c=0;typeof a.mozInnerScreenX!==q&&(b=a.mozInnerScreenX);typeof a.mozInnerScreenY!==q&&(c=a.mozInnerScreenY);return[b,c]};this.IEWindowPosition=function(a){var b,c=0,e=function(a){b=a.screenX-a.clientX;c=a.screenY-a.clientY};a.document.documentElement.attachEvent("onmousemove",e);a.document.documentElement.fireEvent("onmousemove");a.document.documentElement.detachEvent("onmousemove",
e);return[b,c]};this.ComputeVisibility=function(a,b){var c=this.ScreenPos(a),e=b(),d=this.FullWindowSize(a),g=new E,k=g.GetViewportHeight(a),s=g.GetViewportWidth(a);return g.ComputeVisiblePercent(e[0]-c[0],e[1]-c[1],s,k,d[0],d[1],0,0)}}function W(){this.CreateFlashElement=function(a,b,c,e,d,g,k){b=(new Date).getTime();c=document.createElement("div");b="a"+b;c.id=b;a.appendChild(c);a=X;c={id:b,name:b,allowscriptaccess:"always",wmode:"window"};F.switchOffAutoHideShow();F.embedSWF(a,b,1,1,"10.0.1","expressInstall.swf",
{play:"true",loop:"true",quality:"high",allowscriptaccess:"always",allowfullscreen:"false",wmode:"window"},{allowscriptaccess:"always",wmode:"window"},c,e);return b}}function ga(a,f){var c=this,e=(new Date).getTime(),d=new E,g=d.FindObjectPosition(a,window);d.GetHeight(a);d.GetWidth(a);var k=g[1],s=g[0],n=0,h=[],u=!1,t=null;c.engaged=!1;c.noClicks=0;c.totalHoverTime=0;var v=function(b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1},d=function(a){var d=(new Date).getTime()-e,n=Math.floor(a.clientX-
k);a=Math.floor(a.clientY-s);c.engaged=!0;h.push({x:n,y:a});c.noClicks++;var g={};g[b.NO_CLICKS]=c.noClicks;g[b.CLICK_X]=n;g[b.CLICK_Y]=a;g[b.ENGAGEMENT]=c.engaged;g[b.CLICK_TIME]=d/1E3;g[b.EVENT_TYPE]=b.TYPE_CLICK;f.LogEvent(g)},g=function(a){(new Date).getTime();v(a.relatedTarget||a.fromElement)||(u=!0,n=(new Date).getTime(),c.engaged=!0,t=setInterval(function(){if(u){var a=(new Date).getTime();if(0<n){var b=a-n;n=a;c.totalHoverTime+=b}}},1E3))},q=function(a){(new Date).getTime();v(a.relatedTarget||
a.fromElement)||(a=(new Date).getTime(),0<n&&(a-=n,n=0,c.totalHoverTime+=a),u=!1,c.engaged=!0,null!==t&&clearInterval(t),t=null)};a.addEventListener?(a.addEventListener("mouseover",g,!1),a.addEventListener("mouseout",q,!1),a.addEventListener("click",d,!1)):(a.attachEvent("onmouseover",g),a.attachEvent("onmouseout",q),a.attachEvent("onclick",d))}function b(a){var f=Math.floor(9007199254740992*Math.random()),c=0,e={},d=a.parentNode;this.RegisterPlacementData=function(a){e=a};this.LogImpression=function(a){var c;
c=(new Date).getTime();c=Y+"?"+(b.SESSION_ID+"="+encodeURIComponent(f))+"&"+(b.CACHEBUST+"="+encodeURIComponent(c));var d=[],e;for(e in a)a.hasOwnProperty(e)&&d.push(e+"="+encodeURIComponent(a[e]));for(;0!=d.length;)a=d.pop(),c+="&"+a;g(c)};this.LogEvent=function(a){var d=k(),f=d.length;0!=e.size&&(Object.extend(a,e),e={});var h=[],t;for(t in a)a.hasOwnProperty(t)&&h.push(t+"="+encodeURIComponent(a[t]));for(;0!=h.length;)a=h.pop(),a.length+f>b.MAX_URL_LENGTH&&(g(d),c++,d=k(),f=d.length),d+="&"+a;
g(d);c++};this.ParsePlacementArgumentsFromUrl=function(a){var c=a.indexOf("?");if(-1==c)return{};c=a.substring(c+1).split("&");a={};for(var d=0;d<c.length;d++){var g=c[d].split("="),e=decodeURIComponent(g[0]),f="";1<g.length&&(f=decodeURIComponent(g[1]));a[e]=f}c={};a.hasOwnProperty(b.PLACEMENT)&&(c[b.PLACEMENT]=a[b.PLACEMENT]);a.hasOwnProperty(b.CREATIVE)&&(c[b.CREATIVE]=a[b.CREATIVE]);return c};var g=function(a){var b=document.createElement("img");b.src=a;b.width=0;b.height=0;d.appendChild(b)},
k=function(){var a=(new Date).getTime();return Z+"?"+(b.SESSION_ID+"="+encodeURIComponent(f))+"&"+(b.CACHEBUST+"="+encodeURIComponent(a))+"&"+(b.ITEM_NO+"="+encodeURIComponent(c))}}var q="undefined",L="cdn.adamity.com/adamity.js",Z="//event.adamity.com/event",Y="//event.adamity.com/impression",X="//cdn.adamity.com/a.swf";Object.extend=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a};Object.size=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};h.UNKNOWN="Unknown";
h.OPERA="Opera";h.FIREFOX="Firefox";h.CHROME="Chrome";h.SAFARI="Safari";h.IE="IE";h.IE_VERSION_10=10;h.IE_VERSION_9=9;h.IE_VERSION_8=8;h.IE_VERSION_7=7;h.IE_VERSION_6=6;h.IE_VERSION_UNKNOWN="Unknown";E.VISIBILITY_MINIMUM=0.5;var w="hidden";w in document?document.addEventListener("visibilitychange",z):(w="mozHidden")in document?document.addEventListener("mozvisibilitychange",z):(w="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",z):(w="msHidden")in document?document.addEventListener("msvisibilitychange",
z):"onfocusin"in document?document.onfocusin=document.onfocusout=z:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=z;try{window.currentVisibility=document[w]?"hidden":"visible"}catch(oa){window.currentVisibility="visible"}var F=function(){function a(){if(!H){try{var a=m.getElementsByTagName("body")[0].appendChild(m.createElement("span"));a.parentNode.removeChild(a)}catch(b){return}H=!0;for(var a=Q.length,c=0;c<a;c++)Q[c]()}}function b(a){H?a():Q[Q.length]=a}function c(a){if(typeof x.addEventListener!=
p)x.addEventListener("load",a,!1);else if(typeof m.addEventListener!=p)m.addEventListener("load",a,!1);else if(typeof x.attachEvent!=p)I(x,"onload",a);else if("function"==typeof x.onload){var b=x.onload;x.onload=function(){b();a()}}else x.onload=a}function e(){var a=m.getElementsByTagName("body")[0],b=m.createElement(y);b.setAttribute("type",w);var c=a.appendChild(b);if(c){var g=0;(function(){if(typeof c.GetVariable!=p){var e=c.GetVariable("$version");e&&(e=e.split(" ")[1].split(","),l.pv=[parseInt(e[0],
10),parseInt(e[1],10),parseInt(e[2],10)])}else if(10>g){g++;setTimeout(arguments.callee,10);return}a.removeChild(b);c=null;d()})()}else d()}function d(){var a=J.length;if(0<a)for(var b=0;b<a;b++){var c=J[b].id,d=J[b].callbackFn,e={success:!1,id:c};if(0<l.pv[0]){var f=v(c);if(f)if(!A(J[b].swfVersion)||l.wk&&312>l.wk)if(J[b].expressInstall&&k()){e={};e.data=J[b].expressInstall;e.width=f.getAttribute("width")||"0";e.height=f.getAttribute("height")||"0";f.getAttribute("class")&&(e.styleclass=f.getAttribute("class"));
f.getAttribute("align")&&(e.align=f.getAttribute("align"));for(var m={},f=f.getElementsByTagName("param"),u=f.length,q=0;q<u;q++)"movie"!=f[q].getAttribute("name").toLowerCase()&&(m[f[q].getAttribute("name")]=f[q].getAttribute("value"));h(e,m,c,d)}else n(f),d&&d(e);else G(c,!0),d&&(e.success=!0,e.ref=g(c),d(e))}else G(c,!0),d&&((c=g(c))&&typeof c.SetVariable!=p&&(e.success=!0,e.ref=c),d(e))}}function g(a){var b=null;(a=v(a))&&"OBJECT"==a.nodeName&&(typeof a.SetVariable!=p?b=a:(a=a.getElementsByTagName(y)[0])&&
(b=a));return b}function k(){return!K&&A("6.0.65")&&(l.win||l.mac)&&!(l.wk&&312>l.wk)}function h(a,b,c,d){K=!0;$=d||null;ca={success:!1,id:c};var e=v(c);if(e){"OBJECT"==e.nodeName?(P=q(e),R=null):(P=e,R=c);a.id=E;if(typeof a.width==p||!/%$/.test(a.width)&&310>parseInt(a.width,10))a.width="310";if(typeof a.height==p||!/%$/.test(a.height)&&137>parseInt(a.height,10))a.height="137";m.title=m.title.slice(0,47)+" - Flash Player Installation";d=l.ie&&l.win?"ActiveX":"PlugIn";d="MMredirectURL="+x.location.toString().replace(/&/g,
"%26")+"&MMplayerType="+d+"&MMdoctitle="+m.title;b.flashvars=typeof b.flashvars!=p?b.flashvars+("&"+d):d;l.ie&&l.win&&4!=e.readyState&&(d=m.createElement("div"),c+="SWFObjectNew",d.setAttribute("id",c),e.parentNode.insertBefore(d,e),e.style.display="none",function(){4==e.readyState?e.parentNode.removeChild(e):setTimeout(arguments.callee,10)}());u(a,b,c)}}function n(a){if(l.ie&&l.win&&4!=a.readyState){var b=m.createElement("div");a.parentNode.insertBefore(b,a);b.parentNode.replaceChild(q(a),b);a.style.display=
"none";(function(){4==a.readyState?a.parentNode.removeChild(a):setTimeout(arguments.callee,10)})()}else a.parentNode.replaceChild(q(a),a)}function q(a){var b=m.createElement("div");if(l.win&&l.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName(y)[0])if(a=a.childNodes)for(var c=a.length,d=0;d<c;d++)1==a[d].nodeType&&"PARAM"==a[d].nodeName||8==a[d].nodeType||b.appendChild(a[d].cloneNode(!0));return b}function u(a,b,c){var d,e=v(c);if(l.wk&&312>l.wk)return d;if(e)if(typeof a.id==p&&(a.id=c),
l.ie&&l.win){var g="",f;for(f in a)a[f]!=Object.prototype[f]&&("data"==f.toLowerCase()?b.movie=a[f]:"styleclass"==f.toLowerCase()?g+=' class="'+a[f]+'"':"classid"!=f.toLowerCase()&&(g+=" "+f+'="'+a[f]+'"'));f="";for(var k in b)b[k]!=Object.prototype[k]&&(f+='<param name="'+k+'" value="'+b[k]+'" />');e.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+g+">"+f+"</object>";S[S.length]=a.id;d=v(a.id)}else{k=m.createElement(y);k.setAttribute("type",w);for(var h in a)a[h]!=Object.prototype[h]&&
("styleclass"==h.toLowerCase()?k.setAttribute("class",a[h]):"classid"!=h.toLowerCase()&&k.setAttribute(h,a[h]));for(g in b)b[g]!=Object.prototype[g]&&"movie"!=g.toLowerCase()&&(a=k,f=g,h=b[g],c=m.createElement("param"),c.setAttribute("name",f),c.setAttribute("value",h),a.appendChild(c));e.parentNode.replaceChild(k,e);d=k}return d}function t(a){var b=v(a);b&&"OBJECT"==b.nodeName&&(l.ie&&l.win?(b.style.display="none",function(){if(4==b.readyState){var c=v(a);if(c){for(var d in c)"function"==typeof c[d]&&
(c[d]=null);c.parentNode.removeChild(c)}}else setTimeout(arguments.callee,10)}()):b.parentNode.removeChild(b))}function v(a){var b=null;try{b=m.getElementById(a)}catch(c){}return b}function I(a,b,c){a.attachEvent(b,c);M[M.length]=[a,b,c]}function A(a){var b=l.pv;a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&b[1]==a[1]&&b[2]>=a[2]?!0:!1}function B(a,b,c,d){if(!l.ie||!l.mac){var e=m.getElementsByTagName("head")[0];
e&&(c=c&&"string"==typeof c?c:"screen",d&&(N=D=null),D&&N==c||(d=m.createElement("style"),d.setAttribute("type","text/css"),d.setAttribute("media",c),D=e.appendChild(d),l.ie&&l.win&&typeof m.styleSheets!=p&&0<m.styleSheets.length&&(D=m.styleSheets[m.styleSheets.length-1]),N=c),l.ie&&l.win?D&&typeof D.addRule==y&&D.addRule(a,b):D&&typeof m.createTextNode!=p&&D.appendChild(m.createTextNode(a+" {"+b+"}")))}}function G(a,b){if(O){var c=b?"visible":"hidden";H&&v(a)?v(a).style.visibility=c:B("#"+a,"visibility:"+
c)}}function z(a){return null!=/[\\\"<>\.;]/.exec(a)&&typeof encodeURIComponent!=p?encodeURIComponent(a):a}var p="undefined",y="object",w="application/x-shockwave-flash",E="SWFObjectExprInst",x=window,m=document,C=navigator,da=!1,Q=[function(){da?e():d()}],J=[],S=[],M=[],P,R,$,ca,H=!1,K=!1,D,N,O=!0,l=function(){var a=typeof m.getElementById!=p&&typeof m.getElementsByTagName!=p&&typeof m.createElement!=p,b=C.userAgent.toLowerCase(),c=C.platform.toLowerCase(),d=c?/win/.test(c):/win/.test(b),c=c?/mac/.test(c):
/mac/.test(b),b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,e=!+"\v1",f=[0,0,0],g=null;if(typeof C.plugins!=p&&typeof C.plugins["Shockwave Flash"]==y)!(g=C.plugins["Shockwave Flash"].description)||typeof C.mimeTypes!=p&&C.mimeTypes[w]&&!C.mimeTypes[w].enabledPlugin||(da=!0,e=!1,g=g.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),f[0]=parseInt(g.replace(/^(.*)\..*$/,"$1"),10),f[1]=parseInt(g.replace(/^.*\.(.*)\s.*$/,"$1"),10),f[2]=/[a-zA-Z]/.test(g)?parseInt(g.replace(/^.*[a-zA-Z]+(.*)$/,
"$1"),10):0);else if(typeof x.ActiveXObject!=p)try{var k=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");k&&(g=k.GetVariable("$version"))&&(e=!0,g=g.split(" ")[1].split(","),f=[parseInt(g[0],10),parseInt(g[1],10),parseInt(g[2],10)])}catch(h){}return{w3:a,pv:f,wk:b,ie:e,win:d,mac:c}}();(function(){l.w3&&((typeof m.readyState!=p&&"complete"==m.readyState||typeof m.readyState==p&&(m.getElementsByTagName("body")[0]||m.body))&&a(),H||(typeof m.addEventListener!=p&&m.addEventListener("DOMContentLoaded",
a,!1),l.ie&&l.win&&(m.attachEvent("onreadystatechange",function(){"complete"==m.readyState&&(m.detachEvent("onreadystatechange",arguments.callee),a())}),x==top&&function(){if(!H){try{m.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,0);return}a()}}()),l.wk&&function(){H||(/loaded|complete/.test(m.readyState)?a():setTimeout(arguments.callee,0))}(),c(a)))})();(function(){l.ie&&l.win&&window.attachEvent("onunload",function(){for(var a=M.length,b=0;b<a;b++)M[b][0].detachEvent(M[b][1],
M[b][2]);a=S.length;for(b=0;b<a;b++)t(S[b]);for(var c in l)l[c]=null;l=null;for(var d in F)F[d]=null;F=null})})();return{registerObject:function(a,b,c,d){if(l.w3&&a&&b){var e={};e.id=a;e.swfVersion=b;e.expressInstall=c;e.callbackFn=d;J[J.length]=e;G(a,!1)}else d&&d({success:!1,id:a})},getObjectById:function(a){if(l.w3)return g(a)},embedSWF:function(a,c,d,e,g,n,m,q,t,x){var v={success:!1,id:c};l.w3&&!(l.wk&&312>l.wk)&&a&&c&&d&&e&&g?(G(c,!1),b(function(){d+="";e+="";var b={};if(t&&typeof t===y)for(var f in t)b[f]=
t[f];b.data=a;b.width=d;b.height=e;f={};if(q&&typeof q===y)for(var l in q)f[l]=q[l];if(m&&typeof m===y)for(var C in m)f.flashvars=typeof f.flashvars!=p?f.flashvars+("&"+C+"="+m[C]):C+"="+m[C];if(A(g))l=u(b,f,c),b.id==c&&G(c,!0),v.success=!0,v.ref=l;else{if(n&&k()){b.data=n;h(b,f,c,x);return}G(c,!0)}x&&x(v)})):x&&x(v)},switchOffAutoHideShow:function(){O=!1},ua:l,getFlashPlayerVersion:function(){return{major:l.pv[0],minor:l.pv[1],release:l.pv[2]}},hasFlashPlayerVersion:A,createSWF:function(a,b,c){if(l.w3)return u(a,
b,c)},showExpressInstall:function(a,b,c,d){l.w3&&k()&&h(a,b,c,d)},removeSWF:function(a){l.w3&&t(a)},createCSS:function(a,b,c,d){l.w3&&B(a,b,c,d)},addDomLoadEvent:b,addLoadEvent:c,getQueryParamValue:function(a){var b=m.location.search||m.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(null==a)return z(b);for(var b=b.split("&"),c=0;c<b.length;c++)if(b[c].substring(0,b[c].indexOf("="))==a)return z(b[c].substring(b[c].indexOf("=")+1))}return""},expressInstallCallback:function(){if(K){var a=v(E);
a&&P&&(a.parentNode.replaceChild(P,a),R&&(G(R,!0),l.ie&&l.win&&(P.style.display="block")),$&&$(ca));K=!1}}}}(),aa=function(){function a(){if(!d.isReady){try{document.documentElement.doScroll("left")}catch(b){setTimeout(a,1);return}d.ready()}}var b,c,e={"[object Boolean]":"boolean","[object Number]":"number","[object String]":"string","[object Function]":"function","[object Array]":"array","[object Date]":"date","[object RegExp]":"regexp","[object Object]":"object"},d={isReady:!1,readyWait:1,holdReady:function(a){a?
d.readyWait++:d.ready(!0)},ready:function(a){if(!0===a&&!--d.readyWait||!0!==a&&!d.isReady){if(!document.body)return setTimeout(d.ready,1);d.isReady=!0;!0!==a&&0<--d.readyWait||b.resolveWith(document,[d])}},bindReady:function(){if(!b){b=d._Deferred();if("complete"===document.readyState)return setTimeout(d.ready,1);if(document.addEventListener)document.addEventListener("DOMContentLoaded",c,!1),window.addEventListener("load",d.ready,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",
c);window.attachEvent("onload",d.ready);var e=!1;try{e=null==window.frameElement}catch(k){}document.documentElement.doScroll&&e&&a()}}},_Deferred:function(){var a=[],b,c,e,f={done:function(){if(!e){var c=arguments,h,q,s,A,B;b&&(B=b,b=0);h=0;for(q=c.length;h<q;h++)s=c[h],A=d.type(s),"array"===A?f.done.apply(f,s):"function"===A&&a.push(s);B&&f.resolveWith(B[0],B[1])}return this},resolveWith:function(d,f){if(!e&&!b&&!c){f=f||[];c=1;try{for(;a[0];)a.shift().apply(d,f)}finally{b=[d,f],c=0}}return this},
resolve:function(){f.resolveWith(this,arguments);return this},isResolved:function(){return!(!c&&!b)},cancel:function(){e=1;a=[];return this}};return f},type:function(a){return null==a?String(a):e[Object.prototype.toString.call(a)]||"object"}};document.addEventListener?c=function(){document.removeEventListener("DOMContentLoaded",c,!1);d.ready()}:document.attachEvent&&(c=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",c),d.ready())});return function(a){d.bindReady();
d.type(a);b.done(a)}}();b.SESSION_ID="sessionId";b.CACHEBUST="cb";b.ITEM_NO="item";b.PLACEMENT="placement";b.CREATIVE="creative";b.EVENT_TYPE="action";b.AD_DEPTH="addepth";b.TOP_WINDOW_DEPTH="topdepth";b.TOP_URL="topurl";b.ALT_URL_USED="alturl";b.DOMAIN_ANCESTORS="ancestors";b.BROWSER_WINDOW_HEIGHT="brheight";b.BROWSER_WINDOW_WIDTH="brwidth";b.SCREEN_HEIGHT="scheight";b.SCREEN_WIDTH="swidth";b.TIMEZONE="timezone";b.LANGUAGE="lang";b.COOKIE_AVAILABLE="cook";b.IS_TABBED="tabbed";b.IS_OBSTRUCTED="obstruct";
b.AD_WIDTH="adwidth";b.AD_HEIGHT="adheight";b.FRAME_HEIGHT="fheight";b.FRAME_WIDTH="fwidth";b.FRAME_DISPLAY="fdisplay";b.FRAME_OPACITY="fopacity";b.FRAME_VISIBILITY="fvis";b.FLASH_AVAIL="flavail";b.FLASH_MAJOR="flmajor";b.FLASH_MINOR="flminor";b.FLASH_REVISION="flrev";b.BROWSER="brow";b.IE_VERSION="browiev";b.IE_DOC_MODE="browiedoc";b.IE_TRUE_VERSION="browietver";b.INITIAL_BELOW_THE_FOLD="ibtf";b.GEOMETRIC_VISIBILITY_INITIAL_STATE="gvisi";b.NO_CLICKS="clicks";b.ENGAGEMENT="engage";b.CLICK_X="clickx";
b.CLICK_Y="clicky";b.CLICK_TIME="clicktime";b.HOVER_TIME="hovertime";b.GEOMETRIC_VISIBILITY_TOTAL_TIME="gvistotal";b.GEOMETRIC_VISIBILITY_VISIBLE_TIME="gvisvis";b.FLASH_VISIBILITY_TOTAL_TIME="fvistotal";b.FLASH_VISIBILITY_VISIBLE_TIME="fvisvis";b.LAST_EVENT="last";b.ERROR="error";b.TYPE_IMPRESSION="imp";b.TYPE_CLICK="click";b.TYPE_STATUS="status";b.TYPE_ERROR_MAIN="errorMain";b.TYPE_ERROR_INITIAL="errorInitial";b.MAX_URL_LENGTH=2E3;aa(function(){try{var a=new E,f=a.FindScript();null==f&&(f=[document.body,
""]);var c=f[0].parentNode,e=a.FindAd(c);null==e&&(e=c);var d=new b(e),g=d.ParsePlacementArgumentsFromUrl(f[1]);d.RegisterPlacementData(g);d.LogImpression(g);var k=new V,f={};f[b.EVENT_TYPE]=b.TYPE_IMPRESSION;f[b.FLASH_AVAIL]=k.installed;d.LogEvent(f)}catch(s){typeof d==q&&(d=new b(window.document.body.firstChild));f={};f[b.EVENT_TYPE]=b.TYPE_ERROR_INITIAL;f[b.ERROR]=s.message;d.LogEvent(f);return}try{var n=0,f=e;e.parentNode!=q&&(f=e.parentNode);var w=new W,u=null,t=0,v=function(){400<=t||("false"==
k.installed||"function"===typeof u.c&&!isNaN(u.b())?F():(t++,setTimeout(v,100)))},I=new h,A=I.DetectBrowser(),B=I.DetectIEVersion(),G=I.DetectDocumentMode(),z=Math.floor(a.GetWidth(e)/2),p=Math.floor(a.GetHeight(e)/2),y=!1;if(A!=h.IE||B!=h.IE_VERSION_6&&B!=h.IE_VERSION_7&&B!=h.IE_VERSION_8)y=!0;w.CreateFlashElement(f,a.GetWidth(e),a.GetHeight(e),function(a){u=a.ref;setTimeout(function(){u.style.position="absolute"},200);u.style.width="1px";u.style.height="1px";u.style["z-index"]="-100";u.style.opacity=
"0";u.style.filter="alpha(opacity=0)";u.style.top=p+"px";u.style.left=z+"px";y&&(u.style.visibility="hidden");setTimeout(v,100)},A,B,G);var F=function(){var c=new ea,f=c.FindWindowDepth(window),g=c.FindTopReachableWindow(window,f),p=g[0],g=g[1],s=c.SearchTopDownReachable(window.top,g,p),v=!1;null!=s[0]&&(p=s[0],g=s[1],v=!0);var t=function(){return"UNABLE_TO_DETECT"},w=new fa;0==g?t=function(){var b=a.ComputeCurrentlyVisible(e,p);return a.IsVisible(b)}:A==h.FIREFOX?t=function(){var b=w.ComputeVisibility(p,
function(){return w.FirefoxWindowPosition(p)});return a.IsVisible(b)}:A==h.IE&&9<=G&&(t=function(){var b=w.ComputeVisibility(p,function(){return w.IEWindowPosition(p)});return a.IsVisible(b)});var y=0,z=0,E=(new Date).getTime(),s=t(),F=0,H=0,K=(new Date).getTime();if("UNABLE_TO_DETECT"!==t()){var D=function(){var a=(new Date).getTime(),b=(a-E)/1E3;E=a;z+=b;!0===t()&&(y+=b);setTimeout(D,200)};D()}if("false"!=k.installed){var N=function(){var a=(new Date).getTime(),b=(a-K)/1E3;K=a;H+=b;console.log(u.b());
!0===u.c()&&(F+=b);setTimeout(N,200)};N()}var O=new ga(e,d),l=c.DetectUrl(p,g),c=c.GetAncestors(window),L=w.FullWindowSize(p),ba=I.ScreenSize(),V=I.ClientTimezone(),W=I.ClientLanguage(),X=I.CookiesAvailable(),Y=a.IsTabbedOut(),Z=a.CheckForObstruction(e,window),aa=a.GetWidth(e),ha=a.GetHeight(e),ia=a.GetWidth(p.document.body),ja=a.GetHeight(p.document.body),ka=p.document.body.style.display,la=p.document.body.style.opacity,ma=p.document.body.style.visibility,na=I.DetectActualIEBrowserVersion(),T="";
0==g&&(T=a.ComputeInitiallyVisible(e,p),T=a.IsVisible(T));var r={};r[b.EVENT_TYPE]=b.TYPE_STATUS;r[b.AD_DEPTH]=f;r[b.TOP_WINDOW_DEPTH]=g;r[b.TOP_URL]=l;r[b.ALT_URL_USED]=v;r[b.DOMAIN_ANCESTORS]=null===c?"":c.join(",");r[b.BROWSER_WINDOW_HEIGHT]=Math.floor(L[1]);r[b.BROWSER_WINDOW_WIDTH]=Math.floor(L[0]);r[b.SCREEN_HEIGHT]=Math.floor(ba[1]);r[b.SCREEN_WIDTH]=Math.floor(ba[0]);r[b.TIMEZONE]=V;r[b.LANGUAGE]=W;r[b.COOKIE_AVAILABLE]=X;r[b.IS_TABBED]=Y;r[b.IS_OBSTRUCTED]=Z;r[b.AD_WIDTH]=Math.floor(aa);
r[b.AD_HEIGHT]=Math.floor(ha);r[b.FRAME_HEIGHT]=Math.floor(ja);r[b.FRAME_WIDTH]=Math.floor(ia);r[b.FRAME_DISPLAY]=ka;r[b.FRAME_OPACITY]=la;r[b.FRAME_VISIBILITY]=ma;r[b.FLASH_MAJOR]=k.major;r[b.FLASH_MINOR]=k.minor;r[b.FLASH_REVISION]=k.revision;r[b.BROWSER]=A;r[b.IE_VERSION]=B;r[b.IE_DOC_MODE]=G;r[b.IE_TRUE_VERSION]=na;r[b.INITIAL_BELOW_THE_FOLD]=T;r[b.GEOMETRIC_VISIBILITY_INITIAL_STATE]=s;r[b.ENGAGEMENT]=!1;d.LogEvent(r);var U=function(a){typeof a==q&&(a="false");var c={};c[b.EVENT_TYPE]=b.TYPE_STATUS;
c[b.NO_CLICKS]=O.noClicks;c[b.ENGAGEMENT]=O.engaged;c[b.HOVER_TIME]=O.totalHoverTime;c[b.GEOMETRIC_VISIBILITY_TOTAL_TIME]=z;c[b.GEOMETRIC_VISIBILITY_VISIBLE_TIME]=y;c[b.FLASH_VISIBILITY_TOTAL_TIME]=H;c[b.FLASH_VISIBILITY_VISIBLE_TIME]=F;c[b.LAST_EVENT]=a;d.LogEvent(c);n++;a=Math.floor(700*Math.exp(0.4250059*n));setTimeout(U,a)};U();window.addEventListener?window.addEventListener("unload",function(){U("true")},!1):window.attachEvent("onunload",function(){U("true")})}}catch(L){f={},f[b.EVENT_TYPE]=
b.TYPE_ERROR_MAIN,f[b.ERROR]=L.message,d.LogEvent(f)}})})();

