(function(){function W(){var b=this;b.installed=!1;b.raw="";b.major=-1;b.minor=-1;b.revision=-1;b.revisionStr="";var e=[{name:"ShockwaveFlash.ShockwaveFlash.7",version:function(b){return a(b)}},{name:"ShockwaveFlash.ShockwaveFlash.6",version:function(b){var e="6,0,21";try{b.AllowScriptAccess="always",e=a(b)}catch(g){}return e}},{name:"ShockwaveFlash.ShockwaveFlash",version:function(b){return a(b)}}],a=function(b){var e=-1;try{e=b.GetVariable("$version")}catch(a){}return e};b.FlashDetect=function(){var a,
c,g,k,s;if(navigator.plugins&&0<navigator.plugins.length){var l=navigator.mimeTypes;if(l&&l["application/x-shockwave-flash"]&&l["application/x-shockwave-flash"].enabledPlugin&&l["application/x-shockwave-flash"].enabledPlugin.description){a=l=l["application/x-shockwave-flash"].enabledPlugin.description;var l=a.split(/ +/),u=l[2].split(/\./),l=l[3];c=parseInt(u[0],10);g=parseInt(u[1],10);k=l;s=parseInt(l.replace(/[a-zA-Z]/g,""),10)||b.revision;b.raw=a;b.major=c;b.minor=g;b.revisionStr=k;b.revision=
s;b.installed=!0}}else if(-1==navigator.appVersion.indexOf("Mac")&&window.execScript)for(l=-1,u=0;u<e.length&&-1==l;u++){a=-1;try{a=new ActiveXObject(e[u].name)}catch(n){a={activeXError:!0}}a.activeXError||(b.installed=!0,l=e[u].version(a),-1!=l&&(a=l,k=a.split(","),c=parseInt(k[0].split(" ")[1],10),g=parseInt(k[1],10),s=parseInt(k[2],10),k=k[2],b.raw=a,b.major=c,b.minor=g,b.revision=s,b.revisionStr=k))}}()}function n(){this.DetectBrowser=function(){var b=n.UNKNOWN;if(typeof window.opera!==p&&window.opera.buildNumber!==
p)b=n.OPERA;else if(typeof window.mozInnerScreenY!==p)b=n.FIREFOX;else if(typeof window.chrome!==p&&typeof window.chrome.app!==p)b=n.CHROME;else if(typeof window.WebKitPoint!==p)b=n.SAFARI;else if(typeof window.attachEvent!==p||window.documentMode!==p)b=n.IE;return b};this.DetectIEVersion=function(){var b=n.IE_VERSION_UNKNOWN;window.msCrypto?b=n.IE_VERSION_11:window.atob?b=n.IE_VERSION_10:document.addEventListener?b=n.IE_VERSION_9:window.JSON&&document.querySelector?b=n.IE_VERSION_8:window.XMLHttpRequest?
b=n.IE_VERSION_7:document.compatMode&&(b=n.IE_VERSION_6);return b};this.DetectActualIEBrowserVersion=function(){var b=document.createElement("div"),a="Unknown";try{b.style.behavior="url(#default#clientcaps)",a=b.getComponentVersion("{89820200-ECBD-11CF-8B85-00AA005B4383}","componentid").replace(/,/g,".")}catch(c){}return a};this.DetectDocumentMode=function(){return document&&document.documentMode?parseFloat(document.documentMode):n.IE_VERSION_UNKNOWN};this.ScreenSize=function(){return[screen.availWidth,
screen.availHeight]};this.ClientTimezone=function(){return(new Date).getTimezoneOffset()};this.ClientLanguage=function(){return window.navigator.userLanguage||window.navigator.language};this.CookiesAvailable=function(){return navigator.cookieEnabled||"cookie"in document&&(0<document.cookie.length||-1<(document.cookie="test").indexOf.call(document.cookie,"test"))}}function X(){this.FindWindowDepth=function(b){for(var a=0,c=b.top;b!=c&&20>=a;)b=b.parent,a++;20<a&&(a=-1);return a};this.FindTopReachableWindow=
function(b,a){if(-1==a)return[b,a];var c=this.GetAncestors(b);if(null===c)try{for(var f=b.top;b!=f;){b.parent.location.href;if(typeof b.parent.location.href==p)throw new Exception("Access exception");b=b.parent;a--}}catch(d){}else{for(var f=b.location.origin,g=a,k=c.length-1;0<=k;k--)c[k]==f&&(g=k);for(;a!=g;)a--,b=b.parent}return[b,a]};this.SearchTopDownReachable=function(b,a,c){if(0==a||null!==this.GetAncestors(c))return[null,-1];c=[];c.push({win:b,depth:0});for(b=0;0<c.length&&200>=b;){var f=c.shift(),
d=f.win,f=f.depth;if(f>=a)break;try{d.location.href;if(typeof d.location.href==p)throw new Exception("Access exception");return[d,f]}catch(g){}for(var k=0;k<d.frames.length;k++)c.push({win:d.frames[k],depth:f+1});b++}return[null,-1]};this.DetectUrl=function(b,a){return 0==a?b.location.href:b.document.referrer};this.GetAncestors=function(b){b=b.location.ancestorOrigins;var a;a="undefined"===typeof b?"undefined":null===b?"null":Object.prototype.toString.call(b).match(/^\[object\s(.*)\]$/)[1];if("DOMStringList"==
a){a=[];for(var c=0;c<b.length;c++)a[c]=b.item(c).toString();b=a}void 0===b&&(b=null);return b}}function E(){this.FindObjectPosition=function(b,a){return b.getBoundingClientRect?this.FindObjectPositionRect(b,a):this.FindObjectPositionOffset(b)};this.FindObjectPositionOffset=function(b){var a=0,c=0;if(b.offsetParent){do a+=b.offsetLeft,c+=b.offsetTop;while(b=b.offsetParent)}return[c,a]};this.FindObjectPositionRect=function(b,a){var c=b.getBoundingClientRect(),f=a.document.body,d=a.document.documentElement,
g=this.GetPageScroll(a),k=c.left+g[0]-(d.clientLeft||f.clientLeft||0);return[Math.round(c.top+g[1]-(d.clientTop||f.clientTop||0)),Math.round(k)]};this.ComputeVisible=function(b,a,c,f){var d=this.FindObjectPosition(b,a),g=d[0],d=d[1],k=this.GetViewportHeight(a);a=this.GetViewportWidth(a);var s=this.GetHeight(b);b=this.GetWidth(b);return this.ComputeVisiblePercent(d,g,b,s,a,k,c,f)};this.ComputeVisiblePercent=function(b,a,c,f,d,g,k,s){var l=0;0>b?l=Math.max(c+b,0):(l=b-k,l=Math.min(c,Math.min(c+l,d-
l)));d=0;0>a?d=Math.max(f+a,0):(a-=s,d=Math.min(f,Math.min(f+a,g-a)));if(0>l||0>d)return 0;c*=f;return 0>=c?0:d*l/c};this.ComputeInitiallyVisible=function(b,a){return this.ComputeVisible(b,a,0,0)};this.ComputeCurrentlyVisible=function(b,a){var c=this.GetPageScroll(a);return this.ComputeVisible(b,a,c[0],c[1])};this.IsVisible=function(b){return b>=E.VISIBILITY_MINIMUM&&!this.IsTabbedOut()};this.GetPageScroll=function(b){var a,c;b.pageYOffset?(c=b.pageYOffset,a=b.pageXOffset):b.document.documentElement&&
b.document.documentElement.scrollTop?(c=b.document.documentElement.scrollTop,a=b.document.documentElement.scrollLeft):b.document.body&&(c=b.document.body.scrollTop,a=b.document.body.scrollLeft);return[a,c]};this.GetViewportWidth=function(b){return b.document.documentElement.clientWidth};this.GetViewportHeight=function(b){return b.document.documentElement.clientHeight};this.GetWidth=function(b){return parseInt(b.clientWidth)};this.GetHeight=function(b){return parseInt(b.clientHeight)};this.GetSize=
function(b){return[this.GetWidth(b),this.GetHeight(b)]};this.ComputeVolume=function(b){return this.GetWidth(b)*this.GetHeight(b)};this.IsTabbedOut=function(){return"hidden"==window.currentVisibility};this.CheckForObstruction=function(b,a){var c=!1;if(typeof a.document.elementFromPoint!==p){var f=this.FindObjectPosition(b,a),d=this.GetSize(b),f=a.document.elementFromPoint(Math.floor(f[0]+d[0]/2),Math.floor(f[1]+d[1]/2));null!==f&&(c=f!==b)}return c};this.FindScript=function(){for(var b=document.getElementsByTagName("script"),
a=0;a<b.length;a++){var c=b[a].src;if(0<=c.indexOf(Y))return[b[a],c]}return null};this.FindAd=function(b){for(var a=["iframe","img","a","object","embed"],c=null,f=-1,d=0;d<a.length;d++)for(var g=b.getElementsByTagName(a[d]),k=0;k<g.length;k++){var s=g[k],l=this.ComputeVolume(s);l>f&&(f=l,c=s)}return c}}function z(b){var a={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};b=b||window.event;window.currentVisibility=b.type in a?a[b.type]:document[A]?
"hidden":"visible"}function ga(){this.ScreenPos=function(b){var a=0;typeof b.screenX!==p?a=b.screenX:typeof b.screenLeft!==p&&(a=b.screenLeft);var c=0;typeof b.screenY!==p?c=b.screenY:typeof b.screenLeft!=p&&(c=b.screenTop);return[a,c]};this.FullWindowSize=function(a){var e=0,c=0;typeof a.outerWidth!==p&&(e=a.outerWidth);typeof a.outerHeight!==p&&(c=a.outerHeight);return[e,c]};this.FirefoxWindowPosition=function(a){var e=0,c=0;typeof a.mozInnerScreenX!==p&&(e=a.mozInnerScreenX);typeof a.mozInnerScreenY!==
p&&(c=a.mozInnerScreenY);return[e,c]};this.IEWindowPosition=function(a){var e,c=0,f=function(a){e=a.screenX-a.clientX;c=a.screenY-a.clientY};a.document.documentElement.attachEvent("onmousemove",f);a.document.documentElement.fireEvent("onmousemove");a.document.documentElement.detachEvent("onmousemove",f);return[e,c]};this.ComputeVisibility=function(a,e){var c=this.ScreenPos(a),f=e(),d=this.FullWindowSize(a),g=new E,k=g.GetViewportHeight(a),s=g.GetViewportWidth(a);return g.ComputeVisiblePercent(f[0]-
c[0],f[1]-c[1],s,k,d[0],d[1],0,0)}}function Z(){this.CreateFlashElement=function(a,e,c,f,d,g,k){e=(new Date).getTime();c=document.createElement("div");e="a"+e;c.id=e;a.appendChild(c);a=$;c={id:e,name:e,allowscriptaccess:"always",wmode:"window"};F.switchOffAutoHideShow();F.embedSWF(a,e,1,1,"10.0.1","expressInstall.swf",{play:"true",loop:"true",quality:"high",allowscriptaccess:"always",allowfullscreen:"false",wmode:"window"},{allowscriptaccess:"always",wmode:"window"},c,f);return e}}function ha(b,e){var c=
this,f=(new Date).getTime(),d=new E,g=d.FindObjectPosition(b,window);d.GetHeight(b);d.GetWidth(b);var k=g[1],s=g[0],l=0,n=[],I=!1,q=null;c.engaged=!1;c.noClicks=0;c.totalHoverTime=0;var p=function(a){for(;a;){if(a==b)return!0;a=a.parentNode}return!1},d=function(b){var d=(new Date).getTime()-f,l=Math.floor(b.clientX-k);b=Math.floor(b.clientY-s);c.engaged=!0;n.push({x:l,y:b});c.noClicks++;var g={};g[a.NO_CLICKS]=c.noClicks;g[a.CLICK_X]=l;g[a.CLICK_Y]=b;g[a.ENGAGEMENT]=c.engaged;g[a.CLICK_TIME]=d/1E3;
g[a.EVENT_TYPE]=a.TYPE_CLICK;e.LogEvent(g)},g=function(a){(new Date).getTime();p(a.relatedTarget||a.fromElement)||(I=!0,l=(new Date).getTime(),c.engaged=!0,q=setInterval(function(){if(I){var a=(new Date).getTime();if(0<l){var b=a-l;l=a;c.totalHoverTime+=b}}},1E3))},M=function(a){(new Date).getTime();p(a.relatedTarget||a.fromElement)||(a=(new Date).getTime(),0<l&&(a-=l,l=0,c.totalHoverTime+=a),I=!1,c.engaged=!0,null!==q&&clearInterval(q),q=null)};b.addEventListener?(b.addEventListener("mouseover",
g,!1),b.addEventListener("mouseout",M,!1),b.addEventListener("click",d,!1)):(b.attachEvent("onmouseover",g),b.attachEvent("onmouseout",M),b.attachEvent("onclick",d))}function a(b){var e=Math.floor(9007199254740992*Math.random()),c=0,f={},d=b.parentNode;this.RegisterPlacementData=function(a){f=a};this.LogImpression=function(b){var c;c=(new Date).getTime();c=aa+"?"+(a.SESSION_ID+"="+encodeURIComponent(e))+"&"+(a.CACHEBUST+"="+encodeURIComponent(c));var d=[],f;for(f in b)b.hasOwnProperty(f)&&d.push(f+
"="+encodeURIComponent(b[f]));for(;0!=d.length;)b=d.pop(),c+="&"+b;g(c)};this.LogEvent=function(b){var d=k(),e=d.length;0!=f.size&&(Object.extend(b,f),f={});var n=[],q;for(q in b)b.hasOwnProperty(q)&&n.push(q+"="+encodeURIComponent(b[q]));for(;0!=n.length;)b=n.pop(),b.length+e>a.MAX_URL_LENGTH&&(g(d),c++,d=k(),e=d.length),d+="&"+b;g(d);c++};this.ParsePlacementArgumentsFromUrl=function(b){var c=b.indexOf("?");if(-1==c)return{};c=b.substring(c+1).split("&");b={};for(var d=0;d<c.length;d++){var g=c[d].split("="),
f=decodeURIComponent(g[0]),e="";1<g.length&&(e=decodeURIComponent(g[1]));b[f]=e}c={};b.hasOwnProperty(a.PLACEMENT)&&(c[a.PLACEMENT]=b[a.PLACEMENT]);b.hasOwnProperty(a.CREATIVE)&&(c[a.CREATIVE]=b[a.CREATIVE]);return c};var g=function(a){var b=document.createElement("img");b.src=a;b.width=0;b.height=0;d.appendChild(b)},k=function(){var b=(new Date).getTime();return ba+"?"+(a.SESSION_ID+"="+encodeURIComponent(e))+"&"+(a.CACHEBUST+"="+encodeURIComponent(b))+"&"+(a.ITEM_NO+"="+encodeURIComponent(c))}}
var p="undefined",Y="cdn.adamity.com/adamity.js",ba="//event.adamity.com/event",aa="//event.adamity.com/impression",$="//cdn.adamity.com/a.swf";Object.extend=function(a,e){for(var c in e)e.hasOwnProperty(c)&&(a[c]=e[c]);return a};Object.size=function(a){var e=0,c;for(c in a)a.hasOwnProperty(c)&&e++;return e};n.UNKNOWN="Unknown";n.OPERA="Opera";n.FIREFOX="Firefox";n.CHROME="Chrome";n.SAFARI="Safari";n.IE="IE";n.IE_VERSION_11=11;n.IE_VERSION_10=10;n.IE_VERSION_9=9;n.IE_VERSION_8=8;n.IE_VERSION_7=7;
n.IE_VERSION_6=6;n.IE_VERSION_UNKNOWN="Unknown";E.VISIBILITY_MINIMUM=0.5;var A="hidden";A in document?document.addEventListener("visibilitychange",z):(A="mozHidden")in document?document.addEventListener("mozvisibilitychange",z):(A="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",z):(A="msHidden")in document?document.addEventListener("msvisibilitychange",z):"onfocusin"in document?document.onfocusin=document.onfocusout=z:window.onpageshow=window.onpagehide=window.onfocus=
window.onblur=z;try{window.currentVisibility=document[A]?"hidden":"visible"}catch(na){window.currentVisibility="visible"}var F=function(){function a(){if(!N){try{var b=m.getElementsByTagName("body")[0].appendChild(m.createElement("span"));b.parentNode.removeChild(b)}catch(c){return}N=!0;for(var b=J.length,d=0;d<b;d++)J[d]()}}function e(a){N?a():J[J.length]=a}function c(a){if(typeof v.addEventListener!=t)v.addEventListener("load",a,!1);else if(typeof m.addEventListener!=t)m.addEventListener("load",
a,!1);else if(typeof v.attachEvent!=t)M(v,"onload",a);else if("function"==typeof v.onload){var b=v.onload;v.onload=function(){b();a()}}else v.onload=a}function f(){var a=m.getElementsByTagName("body")[0],b=m.createElement(C);b.setAttribute("type",H);var c=a.appendChild(b);if(c){var g=0;(function(){if(typeof c.GetVariable!=t){var f=c.GetVariable("$version");f&&(f=f.split(" ")[1].split(","),h.pv=[parseInt(f[0],10),parseInt(f[1],10),parseInt(f[2],10)])}else if(10>g){g++;setTimeout(arguments.callee,10);
return}a.removeChild(b);c=null;d()})()}else d()}function d(){var a=K.length;if(0<a)for(var b=0;b<a;b++){var c=K[b].id,d=K[b].callbackFn,f={success:!1,id:c};if(0<h.pv[0]){var e=x(c);if(e)if(!w(K[b].swfVersion)||h.wk&&312>h.wk)if(K[b].expressInstall&&k()){f={};f.data=K[b].expressInstall;f.width=e.getAttribute("width")||"0";f.height=e.getAttribute("height")||"0";e.getAttribute("class")&&(f.styleclass=e.getAttribute("class"));e.getAttribute("align")&&(f.align=e.getAttribute("align"));for(var m={},e=e.getElementsByTagName("param"),
q=e.length,p=0;p<q;p++)"movie"!=e[p].getAttribute("name").toLowerCase()&&(m[e[p].getAttribute("name")]=e[p].getAttribute("value"));n(f,m,c,d)}else l(e),d&&d(f);else G(c,!0),d&&(f.success=!0,f.ref=g(c),d(f))}else G(c,!0),d&&((c=g(c))&&typeof c.SetVariable!=t&&(f.success=!0,f.ref=c),d(f))}}function g(a){var b=null;(a=x(a))&&"OBJECT"==a.nodeName&&(typeof a.SetVariable!=t?b=a:(a=a.getElementsByTagName(C)[0])&&(b=a));return b}function k(){return!R&&w("6.0.65")&&(h.win||h.mac)&&!(h.wk&&312>h.wk)}function n(a,
b,c,d){R=!0;ca=d||null;A={success:!1,id:c};var f=x(c);if(f){"OBJECT"==f.nodeName?(Q=p(f),S=null):(Q=f,S=c);a.id=z;if(typeof a.width==t||!/%$/.test(a.width)&&310>parseInt(a.width,10))a.width="310";if(typeof a.height==t||!/%$/.test(a.height)&&137>parseInt(a.height,10))a.height="137";m.title=m.title.slice(0,47)+" - Flash Player Installation";d=h.ie&&h.win?"ActiveX":"PlugIn";d="MMredirectURL="+v.location.toString().replace(/&/g,"%26")+"&MMplayerType="+d+"&MMdoctitle="+m.title;b.flashvars=typeof b.flashvars!=
t?b.flashvars+("&"+d):d;h.ie&&h.win&&4!=f.readyState&&(d=m.createElement("div"),c+="SWFObjectNew",d.setAttribute("id",c),f.parentNode.insertBefore(d,f),f.style.display="none",function(){4==f.readyState?f.parentNode.removeChild(f):setTimeout(arguments.callee,10)}());I(a,b,c)}}function l(a){if(h.ie&&h.win&&4!=a.readyState){var b=m.createElement("div");a.parentNode.insertBefore(b,a);b.parentNode.replaceChild(p(a),b);a.style.display="none";(function(){4==a.readyState?a.parentNode.removeChild(a):setTimeout(arguments.callee,
10)})()}else a.parentNode.replaceChild(p(a),a)}function p(a){var b=m.createElement("div");if(h.win&&h.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName(C)[0])if(a=a.childNodes)for(var c=a.length,d=0;d<c;d++)1==a[d].nodeType&&"PARAM"==a[d].nodeName||8==a[d].nodeType||b.appendChild(a[d].cloneNode(!0));return b}function I(a,b,c){var d,f=x(c);if(h.wk&&312>h.wk)return d;if(f)if(typeof a.id==t&&(a.id=c),h.ie&&h.win){var e="",g;for(g in a)a[g]!=Object.prototype[g]&&("data"==g.toLowerCase()?b.movie=
a[g]:"styleclass"==g.toLowerCase()?e+=' class="'+a[g]+'"':"classid"!=g.toLowerCase()&&(e+=" "+g+'="'+a[g]+'"'));g="";for(var k in b)b[k]!=Object.prototype[k]&&(g+='<param name="'+k+'" value="'+b[k]+'" />');f.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+e+">"+g+"</object>";T[T.length]=a.id;d=x(a.id)}else{k=m.createElement(C);k.setAttribute("type",H);for(var l in a)a[l]!=Object.prototype[l]&&("styleclass"==l.toLowerCase()?k.setAttribute("class",a[l]):"classid"!=l.toLowerCase()&&
k.setAttribute(l,a[l]));for(e in b)b[e]!=Object.prototype[e]&&"movie"!=e.toLowerCase()&&(a=k,g=e,l=b[e],c=m.createElement("param"),c.setAttribute("name",g),c.setAttribute("value",l),a.appendChild(c));f.parentNode.replaceChild(k,f);d=k}return d}function q(a){var b=x(a);b&&"OBJECT"==b.nodeName&&(h.ie&&h.win?(b.style.display="none",function(){if(4==b.readyState){var c=x(a);if(c){for(var d in c)"function"==typeof c[d]&&(c[d]=null);c.parentNode.removeChild(c)}}else setTimeout(arguments.callee,10)}()):
b.parentNode.removeChild(b))}function x(a){var b=null;try{b=m.getElementById(a)}catch(c){}return b}function M(a,b,c){a.attachEvent(b,c);P[P.length]=[a,b,c]}function w(a){var b=h.pv;a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&b[1]==a[1]&&b[2]>=a[2]?!0:!1}function y(a,b,c,d){if(!h.ie||!h.mac){var f=m.getElementsByTagName("head")[0];f&&(c=c&&"string"==typeof c?c:"screen",d&&(da=D=null),D&&da==c||(d=m.createElement("style"),
d.setAttribute("type","text/css"),d.setAttribute("media",c),D=f.appendChild(d),h.ie&&h.win&&typeof m.styleSheets!=t&&0<m.styleSheets.length&&(D=m.styleSheets[m.styleSheets.length-1]),da=c),h.ie&&h.win?D&&typeof D.addRule==C&&D.addRule(a,b):D&&typeof m.createTextNode!=t&&D.appendChild(m.createTextNode(a+" {"+b+"}")))}}function G(a,b){if(E){var c=b?"visible":"hidden";N&&x(a)?x(a).style.visibility=c:y("#"+a,"visibility:"+c)}}function L(a){return null!=/[\\\"<>\.;]/.exec(a)&&typeof encodeURIComponent!=
t?encodeURIComponent(a):a}var t="undefined",C="object",H="application/x-shockwave-flash",z="SWFObjectExprInst",v=window,m=document,B=navigator,O=!1,J=[function(){O?f():d()}],K=[],T=[],P=[],Q,S,ca,A,N=!1,R=!1,D,da,E=!0,h=function(){var a=typeof m.getElementById!=t&&typeof m.getElementsByTagName!=t&&typeof m.createElement!=t,b=B.userAgent.toLowerCase(),c=B.platform.toLowerCase(),d=c?/win/.test(c):/win/.test(b),c=c?/mac/.test(c):/mac/.test(b),b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,
"$1")):!1,f=!+"\v1",e=[0,0,0],g=null;if(typeof B.plugins!=t&&typeof B.plugins["Shockwave Flash"]==C)!(g=B.plugins["Shockwave Flash"].description)||typeof B.mimeTypes!=t&&B.mimeTypes[H]&&!B.mimeTypes[H].enabledPlugin||(O=!0,f=!1,g=g.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),e[0]=parseInt(g.replace(/^(.*)\..*$/,"$1"),10),e[1]=parseInt(g.replace(/^.*\.(.*)\s.*$/,"$1"),10),e[2]=/[a-zA-Z]/.test(g)?parseInt(g.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0);else if(typeof v.ActiveXObject!=t)try{var k=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");
k&&(g=k.GetVariable("$version"))&&(f=!0,g=g.split(" ")[1].split(","),e=[parseInt(g[0],10),parseInt(g[1],10),parseInt(g[2],10)])}catch(l){}return{w3:a,pv:e,wk:b,ie:f,win:d,mac:c}}();(function(){h.w3&&((typeof m.readyState!=t&&"complete"==m.readyState||typeof m.readyState==t&&(m.getElementsByTagName("body")[0]||m.body))&&a(),N||(typeof m.addEventListener!=t&&m.addEventListener("DOMContentLoaded",a,!1),h.ie&&h.win&&(m.attachEvent("onreadystatechange",function(){"complete"==m.readyState&&(m.detachEvent("onreadystatechange",
arguments.callee),a())}),v==top&&function(){if(!N){try{m.documentElement.doScroll("left")}catch(c){setTimeout(arguments.callee,0);return}a()}}()),h.wk&&function(){N||(/loaded|complete/.test(m.readyState)?a():setTimeout(arguments.callee,0))}(),c(a)))})();(function(){h.ie&&h.win&&window.attachEvent("onunload",function(){for(var a=P.length,b=0;b<a;b++)P[b][0].detachEvent(P[b][1],P[b][2]);a=T.length;for(b=0;b<a;b++)q(T[b]);for(var c in h)h[c]=null;h=null;for(var d in F)F[d]=null;F=null})})();return{registerObject:function(a,
b,c,d){if(h.w3&&a&&b){var f={};f.id=a;f.swfVersion=b;f.expressInstall=c;f.callbackFn=d;K[K.length]=f;G(a,!1)}else d&&d({success:!1,id:a})},getObjectById:function(a){if(h.w3)return g(a)},embedSWF:function(a,b,c,d,f,g,l,m,q,p){var O={success:!1,id:b};h.w3&&!(h.wk&&312>h.wk)&&a&&b&&c&&d&&f?(G(b,!1),e(function(){c+="";d+="";var e={};if(q&&typeof q===C)for(var h in q)e[h]=q[h];e.data=a;e.width=c;e.height=d;h={};if(m&&typeof m===C)for(var J in m)h[J]=m[J];if(l&&typeof l===C)for(var u in l)h.flashvars=typeof h.flashvars!=
t?h.flashvars+("&"+u+"="+l[u]):u+"="+l[u];if(w(f))J=I(e,h,b),e.id==b&&G(b,!0),O.success=!0,O.ref=J;else{if(g&&k()){e.data=g;n(e,h,b,p);return}G(b,!0)}p&&p(O)})):p&&p(O)},switchOffAutoHideShow:function(){E=!1},ua:h,getFlashPlayerVersion:function(){return{major:h.pv[0],minor:h.pv[1],release:h.pv[2]}},hasFlashPlayerVersion:w,createSWF:function(a,b,c){if(h.w3)return I(a,b,c)},showExpressInstall:function(a,b,c,d){h.w3&&k()&&n(a,b,c,d)},removeSWF:function(a){h.w3&&q(a)},createCSS:function(a,b,c,d){h.w3&&
y(a,b,c,d)},addDomLoadEvent:e,addLoadEvent:c,getQueryParamValue:function(a){var b=m.location.search||m.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(null==a)return L(b);for(var b=b.split("&"),c=0;c<b.length;c++)if(b[c].substring(0,b[c].indexOf("="))==a)return L(b[c].substring(b[c].indexOf("=")+1))}return""},expressInstallCallback:function(){if(R){var a=x(z);a&&Q&&(a.parentNode.replaceChild(Q,a),S&&(G(S,!0),h.ie&&h.win&&(Q.style.display="block")),ca&&ca(A));R=!1}}}}(),ea=function(){function a(){if(!d.isReady){try{document.documentElement.doScroll("left")}catch(c){setTimeout(a,
1);return}d.ready()}}var e,c,f={"[object Boolean]":"boolean","[object Number]":"number","[object String]":"string","[object Function]":"function","[object Array]":"array","[object Date]":"date","[object RegExp]":"regexp","[object Object]":"object"},d={isReady:!1,readyWait:1,holdReady:function(a){a?d.readyWait++:d.ready(!0)},ready:function(a){if(!0===a&&!--d.readyWait||!0!==a&&!d.isReady){if(!document.body)return setTimeout(d.ready,1);d.isReady=!0;!0!==a&&0<--d.readyWait||e.resolveWith(document,[d])}},
bindReady:function(){if(!e){e=d._Deferred();if("complete"===document.readyState)return setTimeout(d.ready,1);if(document.addEventListener)document.addEventListener("DOMContentLoaded",c,!1),window.addEventListener("load",d.ready,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",c);window.attachEvent("onload",d.ready);var f=!1;try{f=null==window.frameElement}catch(k){}document.documentElement.doScroll&&f&&a()}}},_Deferred:function(){var a=[],b,c,f,e={done:function(){if(!f){var c=
arguments,n,p,s,w,y;b&&(y=b,b=0);n=0;for(p=c.length;n<p;n++)s=c[n],w=d.type(s),"array"===w?e.done.apply(e,s):"function"===w&&a.push(s);y&&e.resolveWith(y[0],y[1])}return this},resolveWith:function(d,e){if(!f&&!b&&!c){e=e||[];c=1;try{for(;a[0];)a.shift().apply(d,e)}finally{b=[d,e],c=0}}return this},resolve:function(){e.resolveWith(this,arguments);return this},isResolved:function(){return!(!c&&!b)},cancel:function(){f=1;a=[];return this}};return e},type:function(a){return null==a?String(a):f[Object.prototype.toString.call(a)]||
"object"}};document.addEventListener?c=function(){document.removeEventListener("DOMContentLoaded",c,!1);d.ready()}:document.attachEvent&&(c=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",c),d.ready())});return function(a){d.bindReady();d.type(a);e.done(a)}}();a.SESSION_ID="sessionId";a.CACHEBUST="cb";a.ITEM_NO="item";a.PLACEMENT="placement";a.CREATIVE="creative";a.EVENT_TYPE="action";a.AD_DEPTH="addepth";a.TOP_WINDOW_DEPTH="topdepth";a.TOP_URL="topurl";a.ALT_URL_USED=
"alturl";a.DOMAIN_ANCESTORS="ancestors";a.BROWSER_WINDOW_HEIGHT="brheight";a.BROWSER_WINDOW_WIDTH="brwidth";a.SCREEN_HEIGHT="scheight";a.SCREEN_WIDTH="swidth";a.TIMEZONE="timezone";a.LANGUAGE="lang";a.COOKIE_AVAILABLE="cook";a.IS_TABBED="tabbed";a.IS_OBSTRUCTED="obstruct";a.AD_WIDTH="adwidth";a.AD_HEIGHT="adheight";a.FRAME_HEIGHT="fheight";a.FRAME_WIDTH="fwidth";a.FRAME_DISPLAY="fdisplay";a.FRAME_OPACITY="fopacity";a.FRAME_VISIBILITY="fvis";a.FLASH_AVAIL="flavail";a.FLASH_MAJOR="flmajor";a.FLASH_MINOR=
"flminor";a.FLASH_REVISION="flrev";a.BROWSER="brow";a.IE_VERSION="browiev";a.IE_DOC_MODE="browiedoc";a.IE_TRUE_VERSION="browietver";a.INITIAL_BELOW_THE_FOLD="ibtf";a.GEOMETRIC_VISIBILITY_INITIAL_STATE="gvisi";a.FLASH_DETECT_NOT_TRUSTED="flashnt";a.NO_CLICKS="clicks";a.ENGAGEMENT="engage";a.CLICK_X="clickx";a.CLICK_Y="clicky";a.CLICK_TIME="clicktime";a.HOVER_TIME="hovertime";a.GEOMETRIC_VISIBILITY_TOTAL_TIME="gvistotal";a.GEOMETRIC_VISIBILITY_VISIBLE_TIME="gvisvis";a.FLASH_VISIBILITY_TOTAL_TIME="fvistotal";
a.FLASH_VISIBILITY_VISIBLE_TIME="fvisvis";a.LAST_EVENT="last";a.ERROR="error";a.TYPE_IMPRESSION="imp";a.TYPE_CLICK="click";a.TYPE_STATUS="status";a.TYPE_ERROR_MAIN="errorMain";a.TYPE_ERROR_INITIAL="errorInitial";a.MAX_URL_LENGTH=2E3;ea(function(){try{var b=new E,e=b.FindScript();null==e&&(e=[document.body,""]);var c=e[0].parentNode,f=b.FindAd(c);null==f&&(f=c);var d=new a(f),g=d.ParsePlacementArgumentsFromUrl(e[1]);d.RegisterPlacementData(g);d.LogImpression(g);var k=new W,e={};e[a.EVENT_TYPE]=a.TYPE_IMPRESSION;
e[a.FLASH_AVAIL]=k.installed;d.LogEvent(e)}catch(s){typeof d==p&&(d=new a(window.document.body.firstChild));e={};e[a.EVENT_TYPE]=a.TYPE_ERROR_INITIAL;e[a.ERROR]=s.message;d.LogEvent(e);return}try{var l=0,u=f;f.parentNode!=p&&(u=f.parentNode);var z=new Z,q=null,x=0,A=function(){var b={};b[a.EVENT_TYPE]=a.TYPE_ERROR_MAIN;b[a.ERROR]="GOT HERE";d.LogEvent(b);50<=x?(b={},b[a.EVENT_TYPE]=a.TYPE_ERROR_MAIN,b[a.ERROR]="Reached polling limit",d.LogEvent(b)):!1==k.installed||"function"===typeof q.addi&&!isNaN(q.addc())?
m():(x++,setTimeout(A,100))},w=new n,y=w.DetectBrowser(),G=w.DetectIEVersion(),L=w.DetectDocumentMode(),t=new X,C=t.FindWindowDepth(window),H=Math.floor(b.GetWidth(f)/2),F=Math.floor(b.GetHeight(f)/2);if(y==n.IE||y==n.FIREFOX)F=H=0;var v=!1;y!=n.FIREFOX&&y!=n.IE&&(v=!0);z.CreateFlashElement(u,b.GetWidth(f),b.GetHeight(f),function(b){q=b.ref;typeof q!=p&&(0!=C||"static"==u.style.position&&""==u.style.position?(setTimeout(function(){q.style.position="absolute";v&&(q.style.visibility="hidden")},200),
q.style.top=F+"px",q.style.left=H+"px"):(b={},b[a.EVENT_TYPE]=a.TYPE_STATUS,b[a.FLASH_DETECT_NOT_TRUSTED]="true",d.LogEvent(b)),q.style.width="1px",q.style.height="1px",q.style["z-index"]="-100",q.style.opacity="0",q.style.filter="alpha(opacity=0)");setTimeout(A,100)},y,G,L);var m=function(){var c=t.FindTopReachableWindow(window,C),e=c[0],c=c[1],g=t.SearchTopDownReachable(window.top,c,e),m=!1;null!=g[0]&&(e=g[0],c=g[1],m=!0);var s=function(){return"UNABLE_TO_DETECT"},u=new ga;0==c?s=function(){var a=
b.ComputeCurrentlyVisible(f,e);return b.IsVisible(a)}:y==n.FIREFOX?s=function(){var a=u.ComputeVisibility(e,function(){return u.FirefoxWindowPosition(e)});return b.IsVisible(a)}:y==n.IE&&9<=L&&10>=L&&(s=function(){var a=u.ComputeVisibility(e,function(){return u.IEWindowPosition(e)});return b.IsVisible(a)});var v=0,x=0,A=(new Date).getTime(),g=s(),z=0,B=0,D=(new Date).getTime();if("UNABLE_TO_DETECT"!==s()){var E=function(){var a=(new Date).getTime(),b=(a-A)/1E3;A=a;x+=b;!0===s()&&(v+=b);setTimeout(E,
100)};E()}if(!1!=k.installed){var F=function(){var a=(new Date).getTime(),c=(a-D)/1E3;D=a;B+=c;!0!==q.addi()||b.IsTabbedOut()||(z+=c);setTimeout(F,100)};F()}var h=new ha(f,d),I=t.DetectUrl(e,c),H=t.GetAncestors(window),M=u.FullWindowSize(e),fa=w.ScreenSize(),W=w.ClientTimezone(),X=w.ClientLanguage(),Y=w.CookiesAvailable(),Z=b.IsTabbedOut(),$=b.CheckForObstruction(f,window),aa=b.GetWidth(f),ba=b.GetHeight(f),ea=b.GetWidth(e.document.body),ia=b.GetHeight(e.document.body),ja=e.document.body.style.display,
ka=e.document.body.style.opacity,la=e.document.body.style.visibility,ma=w.DetectActualIEBrowserVersion(),U="";0==c&&(U=b.ComputeInitiallyVisible(f,e),U=b.IsVisible(U));var r={};r[a.EVENT_TYPE]=a.TYPE_STATUS;r[a.AD_DEPTH]=C;r[a.TOP_WINDOW_DEPTH]=c;r[a.TOP_URL]=I;r[a.ALT_URL_USED]=m;r[a.DOMAIN_ANCESTORS]=null===H?"":H.join(",");r[a.BROWSER_WINDOW_HEIGHT]=Math.floor(M[1]);r[a.BROWSER_WINDOW_WIDTH]=Math.floor(M[0]);r[a.SCREEN_HEIGHT]=Math.floor(fa[1]);r[a.SCREEN_WIDTH]=Math.floor(fa[0]);r[a.TIMEZONE]=
W;r[a.LANGUAGE]=X;r[a.COOKIE_AVAILABLE]=Y;r[a.IS_TABBED]=Z;r[a.IS_OBSTRUCTED]=$;r[a.AD_WIDTH]=Math.floor(aa);r[a.AD_HEIGHT]=Math.floor(ba);r[a.FRAME_HEIGHT]=Math.floor(ia);r[a.FRAME_WIDTH]=Math.floor(ea);r[a.FRAME_DISPLAY]=ja;r[a.FRAME_OPACITY]=ka;r[a.FRAME_VISIBILITY]=la;r[a.FLASH_MAJOR]=k.major;r[a.FLASH_MINOR]=k.minor;r[a.FLASH_REVISION]=k.revision;r[a.BROWSER]=y;r[a.IE_VERSION]=G;r[a.IE_DOC_MODE]=L;r[a.IE_TRUE_VERSION]=ma;r[a.INITIAL_BELOW_THE_FOLD]=U;r[a.GEOMETRIC_VISIBILITY_INITIAL_STATE]=g;
r[a.ENGAGEMENT]=!1;d.LogEvent(r);var V=function(b){typeof b==p&&(b="false");var c={};c[a.EVENT_TYPE]=a.TYPE_STATUS;c[a.NO_CLICKS]=h.noClicks;c[a.ENGAGEMENT]=h.engaged;c[a.HOVER_TIME]=h.totalHoverTime;c[a.GEOMETRIC_VISIBILITY_TOTAL_TIME]=x;c[a.GEOMETRIC_VISIBILITY_VISIBLE_TIME]=v;c[a.FLASH_VISIBILITY_TOTAL_TIME]=B;c[a.FLASH_VISIBILITY_VISIBLE_TIME]=z;c[a.LAST_EVENT]=b;d.LogEvent(c);l++;b=Math.floor(700*Math.exp(0.4250059*l));setTimeout(V,b)};V();window.addEventListener?window.addEventListener("unload",
function(){V("true")},!1):window.attachEvent("onunload",function(){V("true")})}}catch(B){e={},e[a.EVENT_TYPE]=a.TYPE_ERROR_MAIN,e[a.ERROR]=B.message,d.LogEvent(e)}})})();

